import { expect, test, type Page } from '@playwright/test'

async function ready(page: Page) {
  page.on('pageerror', (error) => console.error('PAGE ERROR:', error.stack ?? error.message))
  page.on('console', (message) => {
    if (message.type() === 'error') console.error('BROWSER ERROR:', message.text())
  })
  await page.goto('./')
  await expect(page.locator('canvas')).toHaveAttribute('data-ready', 'true')
}

async function materialCount(page: Page, materialId: number): Promise<number> {
  return page.evaluate((id) => window.__KINETIC_PIXELS__!.count(id), materialId)
}

test.beforeEach(async ({ page }) => {
  await ready(page)
  await page.evaluate(() => localStorage.clear())
})

test('starts with the wooden title, Sand, paused state, and instruction', async ({ page }) => {
  await expect(page.getByRole('button', { name: 'Sand' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByText('Paused')).toBeVisible()
  await expect(page.getByText('Click to play')).toBeVisible()
  expect(await materialCount(page, 4)).toBe(4_800)
})

test('first canvas pointer starts and paints in the same gesture', async ({ page }) => {
  const canvas = page.locator('canvas')
  await canvas.click({ position: { x: 20, y: 20 } })
  await expect(page.getByText('Click to play')).toBeHidden()
  await expect(page.getByRole('button', { name: /Pause/ })).toBeVisible()
  expect(await materialCount(page, 1)).toBeGreaterThan(0)
})

test('a first click on occupied Wood starts without replacing it', async ({ page }) => {
  const canvas = page.locator('canvas')
  const box = await canvas.boundingBox()
  if (!box) throw new Error('Canvas did not render')
  await page.mouse.click(box.x + (42.5 / 320) * box.width, box.y + (107.5 / 300) * box.height)
  await expect(page.getByRole('button', { name: /Pause/ })).toBeVisible()
  expect(await page.evaluate(() => window.__KINETIC_PIXELS__!.cell(42, 107))).toBe(4)
  expect(await materialCount(page, 4)).toBe(4_800)
})

test('Space starts without painting and pause status tracks state', async ({ page }) => {
  await page.keyboard.press('Space')
  await expect(page.getByText('Click to play')).toBeHidden()
  await expect(page.getByText('Paused')).toBeHidden()
  expect(await materialCount(page, 1)).toBe(0)
  await page.keyboard.press('Space')
  await expect(page.getByText('Paused')).toBeVisible()
})

test('paused painting, interpolation, and erasing update immediately', async ({ page }) => {
  await page.keyboard.press('Space')
  await page.keyboard.press('Space')
  await page.getByRole('button', { name: 'Stone' }).click()
  await page.getByLabel('Brush radius').fill('1')
  const canvas = page.locator('canvas')
  const box = await canvas.boundingBox()
  if (!box) throw new Error('Canvas did not render')
  await page.mouse.move(box.x + 35, box.y + 40)
  await page.mouse.down()
  await page.mouse.move(box.x + 200, box.y + 40, { steps: 2 })
  await page.mouse.up()
  expect(await materialCount(page, 3)).toBeGreaterThan(80)
  const beforeErase = await materialCount(page, 3)
  await page.keyboard.press('e')
  await canvas.click({ position: { x: 100, y: 40 } })
  expect(await materialCount(page, 3)).toBeLessThan(beforeErase)
  await expect(page.getByRole('button', { name: /Eraser/ })).toHaveAttribute('aria-pressed', 'true')
  await page.keyboard.press('e')
  await expect(page.getByRole('button', { name: 'Stone' })).toHaveAttribute('aria-pressed', 'true')
})

test('radius shortcuts clamp and adjust the control', async ({ page }) => {
  const slider = page.getByLabel('Brush radius')
  await expect(slider).toHaveValue('5')
  await page.keyboard.press('-')
  await expect(slider).toHaveValue('4')
  await page.keyboard.press('=')
  await expect(slider).toHaveValue('5')
  await page.keyboard.press('+')
  await expect(slider).toHaveValue('6')
})

test('Clear empties the world and reload restores the title', async ({ page }) => {
  await page.getByRole('button', { name: /Clear/ }).click()
  expect(await materialCount(page, 4)).toBe(0)
  await expect(page.getByText('Click to play')).toBeHidden()
  await page.reload()
  await expect(page.locator('canvas')).toHaveAttribute('data-ready', 'true')
  expect(await materialCount(page, 4)).toBe(4_800)
})

test('memory manager pauses, locks shortcuts, ignores backdrop, and closes with Escape', async ({ page }) => {
  await page.keyboard.press('Space')
  await page.getByRole('button', { name: /Memory Card/ }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByText('Paused')).toBeVisible()
  const slider = page.getByLabel('Brush radius')
  await page.keyboard.press('-')
  await page.keyboard.press('=')
  await page.keyboard.press('+')
  await page.keyboard.press('e')
  await page.keyboard.press('Space')
  await expect(slider).toHaveValue('5')
  await expect(page.locator('.play-button')).toContainText('Play')
  await page.locator('.dialog-backdrop').click({ position: { x: 2, y: 2 }, force: true })
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.getByRole('button', { name: /Memory Card/ })).toBeFocused()
})

test('three local slots save, confirm overwrite, load, and delete', async ({ page }) => {
  await page.keyboard.press('Space')
  await page.keyboard.press('Space')
  await page.getByRole('button', { name: 'Stone' }).click()
  await page.locator('canvas').click({ position: { x: 25, y: 25 } })
  const stoneCount = await materialCount(page, 3)
  await page.getByRole('button', { name: /Memory Card/ }).click()
  await page.getByLabel('Slot A save name').fill('ROCK TEST')
  await page.getByRole('region', { name: 'Slot A' }).getByRole('button', { name: 'Save' }).click()
  await expect(page.getByText('Slot A saved.')).toBeVisible()
  await page.getByRole('region', { name: 'Slot A' }).getByRole('button', { name: 'Save' }).click()
  await expect(page.getByText('Replace this save?')).toBeVisible()
  await page.getByRole('button', { name: 'Cancel' }).click()
  await page.getByRole('button', { name: 'Close' }).click()
  await page.getByRole('button', { name: /Clear/ }).click()
  await page.getByRole('button', { name: /Memory Card/ }).click()
  await page.getByRole('region', { name: 'Slot A' }).getByRole('button', { name: 'Load' }).click()
  expect(await materialCount(page, 3)).toBe(stoneCount)
  await expect(page.getByText('Paused')).toBeVisible()
  await page.getByRole('button', { name: /Memory Card/ }).click()
  await page.getByRole('button', { name: 'Delete Slot A' }).click()
  await expect(page.getByText('Slot A deleted.')).toBeVisible()
  await expect(page.getByRole('region', { name: 'Slot A' }).getByRole('button', { name: 'Load' })).toBeDisabled()
  await expect(page.getByRole('region', { name: 'Slot B' }).getByRole('button', { name: 'Load' })).toBeDisabled()
  await expect(page.getByRole('region', { name: 'Slot C' }).getByRole('button', { name: 'Load' })).toBeDisabled()
})

test('JSON export/import round-trips and invalid import preserves the world', async ({ page }) => {
  await page.keyboard.press('Space')
  await page.keyboard.press('Space')
  await page.getByRole('button', { name: 'Stone' }).click()
  await page.locator('canvas').click({ position: { x: 30, y: 30 } })
  const stoneCount = await materialCount(page, 3)
  await page.getByRole('button', { name: /Memory Card/ }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: /JSON Export/ }).click()
  const download = await downloadPromise
  const path = await download.path()
  if (!path) throw new Error('Export did not produce a file')
  await page.getByRole('button', { name: 'Close' }).click()
  await page.getByRole('button', { name: /Clear/ }).click()
  await page.getByRole('button', { name: /Memory Card/ }).click()
  await page.locator('input[type=file]').setInputFiles(path)
  await expect(page.getByRole('dialog')).toBeHidden()
  expect(await materialCount(page, 3)).toBe(stoneCount)
  await page.getByRole('button', { name: /Memory Card/ }).click()
  await page.locator('input[type=file]').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"bad":true}') })
  await expect(page.getByText('Not a Kinetic Pixels save')).toBeVisible()
  expect(await materialCount(page, 3)).toBe(stoneCount)
})
